{% set name = "pybuilder" %}
{% set version = "0.13.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08642b2f5dbf1c47037d3d2000a4f241f9254f5ceb22db324c9f4757f8165075

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - pip

test:
  imports:
    - pybuilder
    - pybuilder.core
  commands:
    - pyb --help  # [unix]

about:
  home: http://pybuilder.github.io/
  license: Apache-2.0
  license_family: Apache
  license_file: pybuilder/LICENSE
  summary: PyBuilder is a software build tool written in 100% pure Python, mainly targeting Python applications.
  description: |
    PyBuilder is based on the concept of dependency based programming,
    but it also comes with a powerful plugin mechanism, allowing the
    construction of build life cycles similar to those known from other
    famous (Java) build tools.
  doc_url: http://pybuilder.github.io/
  dev_url: https://github.com/pybuilder/pybuilder

extra:
  recipe-maintainers:
    - willprice
    - Tobias-Fischer
