{% set name = "pybuilder" %}
{% set version = "0.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85f86d6505ea2457f980b4b01f45514e04b0daf49268fab132233be483d8253b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py==37]

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - pip

test:
  imports:
    - pybuilder
    - pybuilder.core
  commands:
    - pyb --help

about:
  home: http://pybuilder.github.io/
  license: Apache-2.0
  license_family: Apache
  license_file: pybuilder/LICENSE
  summary: PyBuilder is a software build tool written in 100% pure Python, mainly targeting Python applications.
  description: |
    PyBuilder is based on the concept of dependency based programming,
    but it also comes with a powerful plugin mechanism, allowing the
    construction of build life cycles similar to those known from other
    famous (Java) build tools.
  doc_url: http://pybuilder.github.io/
  dev_url: https://github.com/pybuilder/pybuilder

extra:
  recipe-maintainers:
    - willprice
