{% set name = "pybuilder" %}
{% set version = "0.13.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9603ce4ca811a290e40455e6c1f70da38457b7d216eb368d1dc169acb2e7c98e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pip

test:
  imports:
    - pybuilder
    - pybuilder.core
  commands:
    - pyb --help  # [unix]

about:
  home: http://pybuilder.github.io/
  license: Apache-2.0
  license_family: Apache
  license_file: pybuilder/LICENSE
  summary: PyBuilder is a software build tool written in 100% pure Python, mainly targeting Python applications.
  description: |
    PyBuilder is based on the concept of dependency based programming,
    but it also comes with a powerful plugin mechanism, allowing the
    construction of build life cycles similar to those known from other
    famous (Java) build tools.
  doc_url: http://pybuilder.github.io/
  dev_url: https://github.com/pybuilder/pybuilder

extra:
  recipe-maintainers:
    - willprice
    - Tobias-Fischer
